version: "3"
services:
  spring:
    container_name: crit_be
    image: koo3435/crit_be:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: asdkljfhawekjrawmnbvsjachgjhkermn12b34j2151872tdsfzsdbfkjaukjrahm
