
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/post
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        #        show_sql: true
        auto_quote_keyword: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB

file:
  dir: D:/test/


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    practice: DEBUG